version: '3.8'

services:
  robotnik:
    container_name: dev-cmd-bridge-ros2
    image: robotnik/robotnik-ros:builder-foxy-0.9.4-rc2
    volumes:
      - ./postcreate.sh:/home/ros/postcreate.sh
      - ./c_cpp_properties.json:/home/ros/robot_ws/.vscode/c_cpp_properties.json
      - ./ros.repo.yml:/home/ros/repos/ros.repo.yml
      - ../:/home/ros/robot_ws/src/cmd_bridge/:cached
    environment:
      - CC=/usr/bin/gcc
      - CXX=/usr/bin/g++
    command: sleep infinity
    network_mode: host
